### PR TITLE
Adding SystemThermalRandomForcing

### PR DESCRIPTION
**Pull request by tdegeus**

### CODE REVIEW

**Comment by ctu-3u** [comment]
Hello Tom I am really amazed by your completely modified codes. Thank you very much for your help! However I have a little question that it seems now the codes are over-encapsulated. Like for the integral steps, now we use flowSteps to **call** timeSteps to **call** updated_x and updated_v to **call** Computeforce. I am upset to admit that it brings too much complexity for me to read and use the functions...

**Comment by tdegeus** [comment]
Hi @ctu-3u . Yes I understand. This is a tradeoff that is not easy in general. In my proposition, the rule is : the actual implementation is only in **one** place. To take away the complexity that you rightfully point out, one needs a few copies of the same algorithm. That is indeed more readable, and would be the method of choice if we assume that we never change the algorithm (i.e. that we write a code without any error that is also the most efficient one). Unfortunately that is not reality: there are always bugs or suboptimal choices that in the future (may) need attention. Having many copies of the same code is then a huge risk : one **always** forgets to update at least one of the copies (at least those of us that are human ;)).

Now, in many cases one does not need the type of integration that I propose. One could have free functions with a clear input and output. The problem is, however, that for the code we are talking about, I'm simply not clever enough to figure out how to do that, without ending up with (many) re-evaluations and/or copies. The problem there is that this code is time critical: we want to do large/long simulations. 

If you have suggestions, they would be more than welcome. 

As to user complexity. I tried to propose a structure where the user simply should not worry about the internal implementation. All of the public API is 'safe', there is no way how you can forget to call a function. In that sense, what might help you is better documentation, or better (documented) examples?

Please let me know how I can best help you!

**Comment by tdegeus** [comment]
Just some specifics: `flowSteps` is there only not be slowed down by using Python, this is paired with `setRandomForceSequence`. It adds a minor complexity, but I'm not too worried about it. 

Then `timeStep`, yes that is Achilles' heel. It needs to be able to update forces in order to function (that went wrong in https://github.com/tdegeus/FrictionQPotSpringBlock/pull/44 ). So it needs to call `updated_x` and `updated_v` there is really no other way.

**Comment by ctu-3u** [comment]
Hi @tdegeus I finally get your point. Yes it is much clearer to me now! :-)

My suggestion is to make a brief structural description (eg. a plot). Then the latter person knows the level of specific work of each function does. And then they can modify them according to their demands simply. They will know exactly where and how they should touch, not forced to find out each level by themselves, wondering "oh my god why this person cut it into so many pieces". 

As for the temperature forces sequence, now I understand it as a sacrifice of memory to save time. 

My cognitive bias is that I thought these codes as ingredients for research groups. They would have freedom to edit what functions they wanted when using the codes. But now I get the point that, it is more like an engineering product. The users only need to take this, and choose a condition (nonthermal, thermal, etc.) and type in one function to run and get all the results they want.

However, for example, if later we want to have a new class which does not use velocity Verlet to integrate. Also, the force has some different contributions. Then we need to virtualize timeStep(). We write a new timeStep() and it updates force in different ways. So we need also to have new updated_x/v() and Computeforce() to override the old ones. So this means updated() and force() are indeed related to timeStep(). Also, just to mention it, if the codes are expanded to more systems, in this way there will be many virtual functions. And to satisfy the various demands/configurations of systems, we are going to have more levels of functions to call in one integration function. This is opposite to the wish of saving time. First, virtual functions are hardly inline. Because every time we call it, we go to the virtual function table first and find its address and then call it. They cost more time than ordinary functions. Second, calling too many functions also cost more time than we want. So if the codes are to be expanded, to more than these two systems, it seems the current structure might costs more time than we expected. (Just to mention one little wondering of mine. It is not a problem considered now.) By the way, as for what you said as "in many cases one does not need the type of integration that I propose", I feel it happens in many great commercial codes or software (like Matlab). Of course they can accomplish this because they have hired so many programmers and it took them years to work on this. :-)

**Pull request merged**
